Task1/Epam.UsersAwards.MVC/ViewModels/Users/UserListVM.cs
using Epam.UsersAwards.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Epam.UsersAwards.MVC.ViewModels.Users
{
    public class UserListVM
    {
        public IEnumerable<User> Users { get; set; }
    }
}

Task1/Epam.UsersAwards.MVC/Controllers/AwardController.cs
using AutoMapper;
using Epam.UsersAwards.Entities;
using Epam.UsersAwards.MVC.Models;
using Epam.UsersAwards.MVC.ViewModels;
using Epam.UsersAwards.MVC.ViewModels.Awards;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Epam.UsersAwards.MVC.Controllers
{
    public class AwardController : Controller
    {
        private AwardDM awardDm;
        public AwardController(AwardDM awardDm)
        {
            this.awardDm = awardDm;
        }
        // GET: Awards
        public ActionResult Index()
        {
            var awards = awardDm.GetAll();
            ViewBag.Breadcrumb = new Breadcrumb("awards", null, null);
            return View(awards);
        }

        public ActionResult GetByName(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return new HttpStatusCodeResult(400);
            }
            var model = awardDm.GetAwardByName(name);
            ViewBag.Breadcrumb = new Breadcrumb("awards", "search", null);
            return View(model);
        }

        public ActionResult GetByFilter(string filter)
        {
            if (string.IsNullOrEmpty(filter))
            {
                return new HttpStatusCodeResult(400);
            }
            var model = awardDm.GetAwardsByFilter(filter);
            ViewBag.Breadcrumb = new Breadcrumb("awards", "search", null);
            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(Index));
            }
            var award = awardDm.GetAwardByID((int)id);
            if (award == null)
            {
                return HttpNotFound();
            }
            ViewBag.Breadcrumb = new Breadcrumb("award", null, award.Title);
            return View(award);
        }

        // GET: Awards/Create
        public ActionResult Create()
        {
            ViewBag.Breadcrumb = new Breadcrumb("award", "create", null);
            return View();
        }

        // POST: Awards/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AwardCreateVM model)
        {
            ViewBag.Breadcrumb = new Breadcrumb("award", "create", null);
            try
            {
                if (ModelState.IsValid)
                {
                var award = awardDm.Save(model);
                    if(award == null)
                    {
                        ModelState.AddModelError("", "Ошибка при сохранении");
                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", $"{ex.Message}");
                return View();
            }
        }

        // GET: Awards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(400);
            }
            var model = awardDm.GetAwardByID((int)id);
            if(model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Breadcrumb = new Breadcrumb("award", "edit", model.Title);
            return View(Mapper.Map<AwardEditVM>(model));
        }

        // POST: Awards/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AwardEditVM model)
        {
            ViewBag.Breadcrumb = new Breadcrumb("award", "edit", model.Title);
            try
            {
                if (ModelState.IsValid)
                {
                    var award = awardDm.Edit(model);
                    if (award == null)
                    {
                        ModelState.AddModelError("", "Ошибка при сохранении");
                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", $"{ex.Message}");
                return View();
            }
        }

        // GET: Awards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(400);
            }
            var award = awardDm.GetAwardByID((int)id);
            if (award == null)
            {
                return HttpNotFound();
            }
            ViewBag.Breadcrumb = new Breadcrumb("award", "delete", award.Title);
            return View(Mapper.Map<Award>(award));
        }

        // POST: Awards/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Award award)
        {
            try
            {
                ViewBag.Breadcrumb = new Breadcrumb("award", "delete", award.Title);
                var result = awardDm.Delete(award.ID);
                if (result)
                {
                return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Ошибка при удалении");
                    return View();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", $"{ex.Message}");
                return View();
            }
        }
        public ActionResult AwardPartial(int id)
        {
            var award = awardDm.GetAwardByID(id);
            if (award != null)
            {
                return PartialView("_AwardPartialModal", award);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpGet]
        public ActionResult Photo(int id)
        {
            PictureData photo = awardDm.GetPicture(id);
            if (photo == null)
            {
                return File(@"\Content\Images\award-default.png", "image/png");
            }
            return File(photo.Data, photo.ContentType);
        }
        [HttpGet]
        public ActionResult SmallPhoto(int id)
        {
            PictureData photo = awardDm.GetThumbnail(id);
            if (photo == null)
            {
                return File(@"\Content\Images\award-default-small.png", "image/png");
            }
            return File(photo.Data, photo.ContentType);
        }
    }
}

Task1/Epam.UsersAwards.MVC/Controllers/UserController.cs
using AutoMapper;
using Epam.UsersAwards.Entities;
using Epam.UsersAwards.Logic;
using Epam.UsersAwards.LogicContracts;
using Epam.UsersAwards.MVC.Models;
using Epam.UsersAwards.MVC.ViewModels;
using Epam.UsersAwards.MVC.ViewModels.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Epam.UsersAwards.MVC.Controllers
{
    public class UserController : Controller
    {
        private UserDM userDm;
        private AwardDM awardDm;
        public UserController(UserDM userDm, AwardDM awardDm)
        {
            this.userDm = userDm;
            this.awardDm = awardDm;
        }
        // GET: Users
        public ActionResult Index()
        {
            var model = userDm.GetAll();
            ViewBag.Breadcrumb = new Breadcrumb("users", null, null);
            return View(model);
        }

        public ActionResult GetByName(string name)
        {
            ViewBag.Breadcrumb = new Breadcrumb("users", "search", null);
            if (string.IsNullOrEmpty(name))
            {
                return new HttpStatusCodeResult(400);
            }
            var model = userDm.GetUserByName(name);
            return View(model);
        }

        public ActionResult GetByFilter(string filter)
        {
            if (string.IsNullOrEmpty(filter))
            {
                return new HttpStatusCodeResult(400);
            }
            var model = userDm.GetUsersByFilter(filter);
            ViewBag.Breadcrumb = new Breadcrumb("users", "search", null);
            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var user = userDm.GetUserByID((int)id);
            if (user == null)
            {
                return HttpNotFound();
            }
            else
            {
                var model = Mapper.Map<UserShowWithAwardsVM>(user);
                ViewBag.Breadcrumb = new Breadcrumb("user", null, user.Name);
                return View(model);
            }
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.Breadcrumb = new Breadcrumb("user", "create", null);
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserCreateVM model)
        {
            ViewBag.Breadcrumb = new Breadcrumb("user", "create", null);
            try
            {
                if (ModelState.IsValid)
                {
                    var user = userDm.Save(model);
                    if(user == null)
                    {
                        ModelState.AddModelError("", "Ошибка при сохранении");
                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", $"{ex.Message}");
                return View();
            }
        }

        [HttpGet]
        public ActionResult Photo(int id)
        {
            PictureData photo = userDm.GetPicture(id);
            if (photo == null)
            {
                return File(@"\Content\Images\user-default.png", "image/png");
            }
            return File(photo.Data, photo.ContentType);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return HttpNotFound();
            }
            var user = userDm.GetUserByID((int)id);
            if (user == null)
            {
                return HttpNotFound();
            }
            else
            {
                var model = Mapper.Map<UserEditVM>(user);
                ViewBag.Breadcrumb = new Breadcrumb("user", "edit", user.Name);
                return View(model);
            }
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserEditVM model)
        {
            ViewBag.Breadcrumb = new Breadcrumb("user", "edit", model.Name);
            if (ModelState.IsValid)
                {
                    var result = userDm.Edit(model);
                if(result == null)
                {
                    ModelState.AddModelError("", "Ошибка при сохранении");
                    return View();
                }
                return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(400);
            }
            var user = userDm.GetUserByID((int)id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.Breadcrumb = new Breadcrumb("user", "delete", user.Name);
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(UserShowWithAwardsVM user)
        {
            ViewBag.Breadcrumb = new Breadcrumb("user", "delete", user.Name);
            if (userDm.Delete(user.ID))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return new HttpStatusCodeResult(400);
            }
        }
        public ActionResult GetAvaliableAward(int id)
        {
            var user = userDm.GetUserByID(id);
            ViewBag.Breadcrumb = new Breadcrumb("user", "Add award", user.Name);
            if (user != null)
            {
                var awards = awardDm.GetAll();
                user.Awards = awards.Except(user.Awards).ToList();
                return View(user);
            }
            else
            {
                return HttpNotFound();
            }
        }
        public ActionResult AddAward(int userID, int awardID)
        {
            try
            {
                userDm.AddAwardToUser(userID, awardID);
                return RedirectToAction(nameof(Index));
            }
            catch 
            {
                return new HttpStatusCodeResult(400);
            }
        }

        public FileResult GetAllAsFile()
        {
            byte[] usersBytes = userDm.GetAllAsFile();
            return File(usersBytes, System.Net.Mime.MediaTypeNames.Application.Octet, "Users.txt");
        }
    }
}

Task1/Epam.UsersAwards.MVC/Controllers/UsersController.cs
using AutoMapper;
using Epam.UsersAwards.Entities;
using Epam.UsersAwards.Logic;
using Epam.UsersAwards.LogicContracts;
using Epam.UsersAwards.MVC.Models;
using Epam.UsersAwards.MVC.ViewModels;
using Epam.UsersAwards.MVC.ViewModels.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Epam.UsersAwards.MVC.Controllers
{
    public class UsersController : Controller
    {
        private UserDM userDm;

        public UsersController(UserDM userDm)
        {
            this.userDm = userDm;
        }
        // GET: Users
        public ActionResult Index()
        {
            var users = userDm.GetAll();
            return View(users);
        }

        public ActionResult GetByName(string name)
        {
            return View(userDm.GetUserByName(name));
        }

        public ActionResult GetByFilter(string filter)
        {
            return View(userDm.GetUsersByFilter(filter));
        }
        public ActionResult GetByID(int id)
        {
            return View(userDm.GetUserForEdit(id));
        }
        // GET: Users/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(UserCreateVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userDm.Save(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Photo(int id)
        {
            PictureData photo = userDm.GetPicture(id);
            if (photo == null)
            {
                return File(@"\Content\Images\anonymous-user.png", "image/png");
            }
            return File(photo.Data, photo.ContentType);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int id)
        {
            var model = userDm.GetUserForEdit(id);
            return View(model);
        }

        // POST: Users/Edit/5
        [HttpPost]
        public ActionResult Edit(UserEditVM model)
        {
            //try
            //{
                userDm.Edit(model);
                return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Users/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                userDm.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult AddAward(int userID, int awardID)
        {
            try
            {
                userDm.AddAwardToUser(userID, awardID);
                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }
    }
}

Task1/Epam.UsersAwards.MVC/Views/User/Create.cshtml
@model Epam.UsersAwards.MVC.ViewModels.UserCreateVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Task1/Epam.UsersAwards.MVC/Views/User/Delete.cshtml
@model Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
@Html.Partial("_UserPartial", Model)
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Task1/Epam.UsersAwards.MVC/Views/User/Details.cshtml
@model Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Details</h2>

<div>
@Html.Partial("_UserPartial", Model)
</div>

Task1/Epam.UsersAwards.MVC/Views/User/Edit.cshtml
@model Epam.UsersAwards.MVC.ViewModels.Users.UserEditVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Task1/Epam.UsersAwards.MVC/Views/User/GetAvaliableAward.cshtml
@model Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM
@{
    ViewBag.Title = "Add award to user";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Add Award to User</h2>

@using (Html.BeginForm("AddAward", "User", new { userID = Model.ID }, FormMethod.Post, new { @class = "form-inline" }))
{
    
            <div class="form-group dropdown">
            <label for="awardID">Add award</label>
            @Html.DropDownList("awardID",new SelectList(Model.Awards, dataValueField: "ID", dataTextField: "Title"), new { @class = "form-control" })
        </div>
        <fieldset disabled class="form-group">
            <div class="form-group">
                <label for="disabledSelect">to user with ID</label>
                <select id="disabledSelect" class="form-control">
                    <option>@Model.ID</option>
                </select>
            </div>
        </fieldset>
    <button type="submit" class="btn btn-primary">Submit</button>
}

Task1/Epam.UsersAwards.MVC/Views/User/GetByFilter.cshtml
@model IEnumerable<Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM>

@{
    ViewBag.Title = "GetByFilter";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Search</h2>

@foreach (var item in Model) {
@Html.Partial("_UserPartial", item)
}

Task1/Epam.UsersAwards.MVC/Views/User/GetByName.cshtml
@model Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM

@{
    ViewBag.Title = "GetByName";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Search</h2>

<div>
    @Html.Partial("_UserPartial", Model)
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Task1/Epam.UsersAwards.MVC/Views/User/Index.cshtml
@model IEnumerable<Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM>
@section scripts{
<script src="~/Scripts/tooltip-toggle.js"></script>
<script src="~/Scripts/awards-modal.js"></script>
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<h2>Index</h2>
<div class="row">
    <button type="button" class="btn btn-default btn-lg pull-left">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>@Html.ActionLink("Create New", "Create")
    </button>
    
    <button type="button" class="btn btn-default btn-lg pull-right">
    <span class="glyphicon glyphicon-download" aria-hidden="true"></span>@Html.ActionLink("Download All", "GetAllAsFile")
    </button>
</div>
    @foreach (var item in Model)
{
    @Html.Partial("_UserPartial", item)
  
}
<div id="modDialog" class="modal fade" tabindex="-1" role="dialog" >
<div  class="modal-dialog" role="document">
    <div class="modal-content" id="dialogContent">
    </div>
</div>
</div>

Task1/Epam.UsersAwards.MVC/Views/User/_UserPartial.cshtml
@model Epam.UsersAwards.MVC.ViewModels.Users.UserShowWithAwardsVM
<div class="row panel panel-default">
    <figure class="col-md-4 col-sm-6 col-xs-12 pull-left">
        <img src="@Url.Action("Photo","User", new { id = Model.ID })" alt="@Model.Name's photo" width="250" height="250" class="img-rounded img-thumbnail">
    </figure>    
    <div class="col-md-8 col-sm-6 col-xs-12 pull-right">
        <header>
            <h3>@Model.Name</h3>
        </header>
        <section>
            <h4>Date of birth: @Model.DOB.ToShortDateString() (@Model.Age)</h4>
        </section>

        <section>
            <h4>Awards:</h4>
                @if (!Model.Awards.Any())
                {
                    <p>No availible awards for this user</p>
                }
                else
                {
                    <div class="row">
                        @foreach (var award in Model.Awards)
                        {

                        <div class="col-xs-6 col-md-2 col-sm-4">
                            <a href="@Url.Action("AwardPartial", "Award", new { id = award.ID })" class="thumbnail modalItem" data-toggle="tooltip" data-placement="top" title="@award.Title">
                                <img src="@Url.Action("SmallPhoto", "Award", new { id = award.ID })" alt="@award's photo" width="50" height="50" class="img-circle img-thumbnail">
                            </a>
                        </div>
                        }
                    </div>
                }
        </section>
        <div>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Add award", "GetAvaliableAward", new { id = Model.ID }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Delete", "Delete", new { id = Model.ID }, new { @class = "btn btn-danger" })
            
        </div>
    </div>
</div>